package com.example.weather.utils

const val YANDEX_API_KEY = "X-Yandex-API-Key"

const val SP_DB_LOCATION = "SP_DB_LOCATION"
const val SP_DB_LOCATION_KEY = "SP_DB_LOCATION_KEY"

const val LOCATION_RUSSIAN = "LOCATION_RUSSIAN"
const val LOCATION_USA = "LOCATION_USA"
const val LOCATION_WORLD = "LOCATION_WORLD"

const val ROOM_DB_WEATHER = "ROOM_DB_WEATHER"

const val CONTENT_PROVIDER_FRAGMENT_TAG = "CONTENT_PROVIDER_FRAGMENT_TAG"
const val WEATHER_HISTORY_LIST_FRAGMENT_TAG = "WEATHER_HISTORY_LIST_FRAGMENT_TAG"
const val MAPS_FRAGMENT_TAG = "MAPS_FRAGMENT_TAG"



const val REQUEST_CODE_LOCATION = 997
const val REQUEST_CODE_READ_CONTACTS = 999
const val REQUEST_CODE_CALL = 998


/**********
FCM
 ********/
const val CHANNEL_HIGH_ID = "channel_we3tw43"
const val NOTIFICATION_ID1 = 1

const val NOTIFICATION_KEY_TITLE = "myTitle"
const val NOTIFICATION_KEY_BODY = "myBody"
/**********/

const val BuildConfig_WEATHER_API_KEY = "9d8f52b7-e22d-45fe-b38a-505e9c40b6f3"