package com.example.weather.utils

const val YANDEX_API_KEY = "X-Yandex-API-Key"

const val SP_DB_LOCATION = "SP_DB_LOCATION"
const val SP_DB_LOCATION_KEY = "SP_DB_LOCATION_KEY"

const val LOCATION_RUSSIAN = "LOCATION_RUSSIAN"
const val LOCATION_USA = "LOCATION_USA"
const val LOCATION_WORLD = "LOCATION_WORLD"

const val ROOM_DB_WEATHER = "ROOM_DB_WEATHER"

const val CONTENT_PROVIDER_FRAGMENT_TAG = "CONTENT_PROVIDER_FRAGMENT_TAG"